### ISSUE TITLE
Not working on Android's Private DNS?

### ISSUE THREAD

**Issue by HotCakeX** [serverless-dns/serverless-dns#107]
I tried using Max and Sky, also tried using my own Cloudflare hosted server-less DoH, on Android private DNS, but it never works. I use Android 13 so it supports both DoT and DoH.

is this expected and the only way to use it on Android is through the app?

**Comment by ignoramous** [comment]
Android Private DNS supports DoT only (`max.rethinkdns.com`). So, you'd not be able to use Cloudflare serverless (`sky.rethinkdns.com`) there.

Can you check if your ISP isn't blocking DoT and/or RethinkDNS servers?

**Comment by HotCakeX** [comment]
> Android Private DNS supports DoT only (`max.rethinkdns.com`). So, you'd not be able to use Cloudflare serverless (`sky.rethinkdns.com`) there.
> 
> Can you check if your ISP isn't blocking DoT and/or RethinkDNS servers?

My ISP provides DoT and I can use theirs on Android private DNS, so DoT isn't entirely blocked, but when I enter "max.rethinkdns.com" or my own serverless-DNS DoT hosted on Cloudflare, it won't work.
at the same time, on Windows, browser and Android app of rethink, I can use "https://max.rethinkdns.com/" and my own serverless-DNS DoH without any issue.

so what do you think is going on?

**Comment by HotCakeX** [comment]
Also when I said Android 13 supports DoH
https://twitter.com/MishaalRahman/status/1549490518190706689

**Comment by ignoramous** [comment]
Not really. Google limits DoH to just Cloudflare and Google. No other DoH resolver is allowed or would work.

----

Re: DoT: Are you able to connect to `dns.adguard-dns.com` and `dns.quad9.net` with Private DNS?

> https://max.rethinkdns.com/

Btw, not sure if you know, but with DoT (Private DNS), you'd need to enter `max.rethinkdns.com` without any of the slashes (`/`) or protocols +`https://`).

**Comment by HotCakeX** [comment]
> Not really. Google limits DoH to just Cloudflare and Google. No other DoH resolver is allowed or would work.
> 
> Re: DoT: Are you able to connect to `dns.adguard-dns.com` and `dns.quad9.net` with Private DNS?
> 
> > https://max.rethinkdns.com/
> 
> Btw, not sure if you know, but with DoT (Private DNS), you'd need to enter `max.rethinkdns.com` without any of the slashes (`/`) or protocols (`https://`).

Yes I can connect to Adguard and Quad9, the private DNS section doesn't even allow for `//` or `:`, only accepts words, numbers and `.`.

if for some reason, `max.rethinkdns.com` was blocked, does it mean that my own serverless-DNS `MyPrivateDNS.workers.dev` also gets blocked?

**Comment by ignoramous** [comment]
Any deployments to `workers.dev` cannot support DoT only DoH. For DoT, you'd have to deploy serverless-dns to Fly.io

See if `nx.rethinkdns.com` works? It points to the same server as `max.rethinkdns.com`.

**Comment by HotCakeX** [comment]
> Any deployments to `workers.dev` cannot support DoT only DoH. For DoT, you'd have to deploy serverless-dns to Fly.io
> 
> See if `nx.rethinkdns.com` works? It points to the same server as `max.rethinkdns.com`.

it doesn't, still says "couldn't connect", but that's okay, I will keep using rethink app on phone when I need it on my phone, thank you anyway,
problem must be on my network blocking max.rethinkdns.com DoT but allowing it to be used as DoH on other devices.
mobile OSes are annoying for me for these reasons, very little functionality without root and when you root, you lose OTA updates and other things.
