### ISSUE TITLE
Incomplete string escaping or encoding

### ISSUE THREAD

**Issue by SpencerIsGiddy** [serverless-dns/serverless-dns#136]
codeql is flagging [line 514](https://github.com/serverless-dns/serverless-dns/blob/1366f86d19760d591b295c7bc689d3a0aeae7056/src/server-node.js#L514) as not escaping backslash characters. It says… “This does not escape backslash characters in the input”

not sure if this is a security false positive but this is the only codeql flag that appeared after setting up codeql and running it multiple times

![IMG_3379](https://user-images.githubusercontent.com/109806759/225335587-79170f6b-497b-47d2-a75f-750989c51b47.png)

**Comment by ignoramous** [comment]
Not sure what codeql means, but the current code works as expected. @amithm7 wrote it, may be he has some inputs on why the regexe pattern is the way it is.

**Comment by SpencerIsGiddy** [comment]
Doing the line as…
`const d = entry.replace(/\./g, ",\\.");`
Fixes the issue. Lint and the codespace cleanthat didn’t [flag it as problematic](https://github.com/SpencerIsGiddy/serverless-dns/pull/10) ,

**Comment by SpencerIsGiddy** [comment]
Sorry about that @amithm7 . I accidentally forgot to revert a commit I was testing and that’s why there are 3 \, Il update my screenshot with one after my latest scan cause it still appears. Il try to see why the lines are different

**Comment by SpencerIsGiddy** [comment]
Ok, so update.

I found the solution to the security risk

`const d = entry.replace(/\\./g, "\\\\.");` fixes the issue.

Hears what chatgpt had to say when I asked it about it

“ This code uses double backslashes "\" to escape each backslash character in the regular expression pattern and in the replacement string. By doing so, you ensure that the backslash characters are properly escaped and the resulting string is safe from injection attacks.”

so it seems like two backslashes were needed to represent one 

does this seem correct?

**Comment by amithm7** [comment]
The current code `const d = entry.replace(/\./g, "\\.");` does this for an `entry`.

It replaces `.` by `\.` (required for constructing a Regular Expression, comments on the code are bit misleading, only one `\` appears in the replacement, other is for escaping it)

![image](https://user-images.githubusercontent.com/7036770/225554529-7fb0ec3f-beb0-4b39-bcea-382c30506d36.png)

> const d = entry.replace(/\\./g, "\\\\."); fixes the issue.

It may fix the warning, but won't work. `/\\./g` won't match `.`.
And if matched, `\\\\.` will replace `.` with `\\.`, which is not part of the required Regular Expression.

The alert may be dismissed, the `entry` is not coming from user input; it comes from TLS CA Certificate put on server. So, it is not a security issue.

Comments on the code may be corrected though, with a single `\`.

**Comment by SpencerIsGiddy** [comment]
CodeQL no longer flags it after switching to the line you have given.

Good to know that even with the current way it is. Even though it gets flagged, it isn’t a security issue that affects the user

**Comment by amithm7** [comment]
Great, then `replaceAll` can be used.
