### ISSUE TITLE
Does cloudflare overstate how many requests are being sent?

### ISSUE THREAD

**Issue by SpencerIsGiddy** [serverless-dns/serverless-dns#137]
So I’ve noticed that I’m constantly over 17k requests daily on cloudflare which seems quite high for me since I have my cache_ttl set at 86400 (1d) and my cache-utils.js ttl are set at 15m min and 1d max. Is there something I’m forgetting about that would explain it to be so high?

**Comment by ignoramous** [comment]
Server-side caching parameters have no change in number of incoming requests.

Currently, there's no way to specify higher TTLs for client-side caching.

(I personally don't think Cloudflare overstates incoming request count).

**Comment by SpencerIsGiddy** [comment]
Hmm, interesting

**Comment by SpencerIsGiddy** [comment]
Oh and another question. Is requests the same thing as queries?

**Comment by ignoramous** [comment]
Typically, serverless-dns is only serving dns queries, so yes, one request == one query
