### ISSUE TITLE
Would a rate limiter be of any use?

### ISSUE THREAD

**Issue by SpencerIsGiddy** [serverless-dns/serverless-dns#144]
So I’ve created a rate limiter that could be implemented into serverless-dns if there is of any use for it for an extra security provision. It is currently a very rough draft and I’m not entirely sure if the limit is individually or on a server such as a whole cloudflare worker. Any thoughts on this would help https://github.com/SpencerIsGiddy/serverless-dns/pull/15/files

**Comment by ignoramous** [comment]
load shed aggressively as loadavg (not the best metric) -> 1 https://github.com/serverless-dns/serverless-dns/commit/69fa6c0ff214fa5d2e01b9e98ed0cec5e7143334
