### ISSUE TITLE
Private DNS issue on Android 12

### ISSUE THREAD

**Issue by MetalGeek464** [serverless-dns/serverless-dns#145]
When I attempt to use max.rethinkdns.com as my Private DNS on my LGV60, DNS resolution stops working.  I've tried rebooting my phone, and I've tried other Private DNS options and they work.  p2.freedns.controld.com is currently working without incident.  The previous issue regarding this on Android 13 didn't yield a solution other than using the App on Android.  Is that the only solution at this point in time?

**Comment by ignoramous** [comment]
In the past 2 days, we got hammered in LA, Frankfurt, Chennai, and Singapore. Were you connecting from anywhere close to those regions? If so, that might explain why Private DNS may not have worked for you. We need to code up a traffic-control / bot management into our deployments on Fly (on Cloudflare, we get that for free) to avoid being DoSd, which is frankly a frequent occurrence these days.

Other than that, `max.rethinkdns.com` should have been working. I don't see any ongoing problems on the servers/resolvers, right now.

**Comment by MetalGeek464** [comment]
Thank you.  It was working via the App.  I'm in North California. Not sure if LA = Los Angeles or Louisiana. If it's LA, then that could account for the blockage.

**Comment by ignoramous** [comment]
LAX, yes. I'll explore implementing some rudimentary mitigation, because DoS has become super common.

**Comment by ignoramous** [comment]
We've added a bunch of controls for the current level of traffic (~1.5b reqs/day), but beyond that DoS remains a credible downtime threat.
