### ISSUE TITLE
deploy doesnt work

### ISSUE THREAD

**Issue by asterriya** [serverless-dns/serverless-dns#15]
Trying to deploy via button, but it doesn't work. Always redirect to here https://github.com/serverless-dns/serverless-dns

**Comment by ignoramous** [comment]
cc: @santhosh-ponnusamy

**Comment by ignoramous** [comment]
@asterriya can you try now? Looks like you may need to refresh the page once or twice and then, seemingly by magic, one-click deploys start working again.

**Comment by asterriya** [comment]
Still the same error

**Comment by santhosh-ponnusamy** [comment]
On clicking deploy button, you are redirected to this page?
![Screenshot_2021-08-24-07-00-09-90_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/67677652/130541375-8001ec70-09f9-4e25-94e9-2922491d768a.jpg)

**Comment by asterriya** [comment]
redirecting to github source again

**Comment by santhosh-ponnusamy** [comment]
Browser used?
Can you please try at private browsing mode.
Login to git hub
https://github.com/serverless-dns/serverless-dns/
Click on deploy button

**Comment by asterriya** [comment]
Chrome 90, logged in github
Pressed on button but still the same

**Comment by asterriya** [comment]
Found the bug, and now it's redirecting to the Cloudflare worker. But now I have a question, how to change Cloudflare DNS to another one? Read instruction and still don't understand.

**Comment by ignoramous** [comment]
> Found the bug,

What was it?

> Read instruction and still don't understand.

If you are not technical that it might be a step too far. The instructions basically ask you to edit "Environment Variables" of the serverless-dns Workers you're deploying from Cloudflare's Workers dashboard.

Alternatively, you could fork this project and permanently edit the configuration. Specifically `CF_DNS_RESOLVER_URL` in https://github.com/serverless-dns/serverless-dns/blob/465f49348e7de478b4c1d90097b918ef2ec89ddc/wrangler.toml#L9

**Comment by ignoramous** [comment]
Hi OP, feel free to reopen this bug in case the workaround you found stopped working. Thanks.
