### ISSUE TITLE
I did everything right?

### ISSUE THREAD

**Issue by Lucas559-noob** [serverless-dns/serverless-dns#156]
I did it with Cloudflare workers, but now idk if is everything right as should be.
On Cloudflare workers, it shows serverless-dns as should be, on settings, variables are with Cloudflare as cloud platform.
Also, configured the DNS with the filters I want for my browser, but now I don't know if they work or if I did something wrong.

Using https://www.dnsleaktest.com/  on extended, it shows a lot of Google servers, is this right?
![image](https://user-images.githubusercontent.com/54007604/235735027-7f20eadb-6ffe-47e2-add0-468250b55a3b.png)

**Comment by ignoramous** [comment]
Hi there,

Yeah, `Google` and `Cloudflare` servers are what you should see, so it *seems* to be working. You can try visiting a domain you think must be have been blocked with the blocklists you've configured... [`segment.io`](https://rethinkdns.com/search?s=1%3AYAYBACABEDAgAA%3D%3D&q=segment.io) for example is blocked by `rec.max.rethinkdns.com`.

If you want your serverless-dns deployment on Workers to point to some other upstream DoH resolver (upstream must be DoH), then add / modify `CF_DNS_RESOLVER` and `CF_DNS_RESOLVER_2` env variables ([code](https://github.com/serverless-dns/serverless-dns/blob/f0ae0d653dce42321dae432f27b0fcfc90d81901/src/core/env.js#L116-L124)).

**Comment by ignoramous** [comment]
Please feel free to reopen in case you're unable to get it to work. Thanks
