### ISSUE TITLE
how te see dns logs

### ISSUE THREAD

**Issue by kloudxyz** [serverless-dns/serverless-dns#162]
Hi,

How can we see the dns logs, and what is blocked and bypassed?

**Comment by ignoramous** [comment]
Are you deploying your own instance of `serverless-dns`, then see #17 If not, there's no way to do so, right now. We are working on it. Likely to land in a month or two.

**Comment by kloudxyz** [comment]
yes deployed on cloudflare.
Ok great will wait for it then

**Comment by ignoramous** [comment]
Gotcha. Closing it as dup of #17
