### ISSUE TITLE
I keep seeing Google as DNS resolver

### ISSUE THREAD

**Issue by HotCakeX** [serverless-dns/serverless-dns#168]
I set my custom DNS over HTTPS server for Cloudflare worker to NextDNS and when i'm at the home page of NextDNS website, i keep seeing Google DNS intermittently.

I found a Google resolver in the worker.js

can I safely remove this part or even replace it with another DoH without triggering any problems further down the road?

```js
      CF_DNS_RESOLVER_URL_2: {
        type: "string",
        default: "https://dns.google/dns-query"
      },
```

Will removing/replacing this part fix my problem?

Thanks in advance

**Comment by ignoramous** [comment]
You could set it to the same NextDNS resolver, yes. Set this as an env variable (of the same name) from your Cloudflare Workers dashboard (no need to change code): https://developers.cloudflare.com/workers/platform/environment-variables/

**Comment by HotCakeX** [comment]
@ignoramous thank you!
