### ISSUE TITLE
Is/Will the configuration page open sourced?

### ISSUE THREAD

**Issue by lwd-temp** [serverless-dns/serverless-dns#169]
I've noticed that this project uses `https://rethinkdns.com/configure` to generate service URL, but I cannot find the configure page's source code.

Is/Will the configure page be open sourced?

**Comment by lwd-temp** [comment]
I've seen this [here](https://rethinkdns.com/faq):

> The AWS backend and the website sources are closed, primarily because the code is very specific to the infrastructure we have built and it is likely in an incomprehensible and inconsumable state from all the constant influx in changes that it sees on a day-to-day basis.

**Comment by ignoramous** [comment]
We could open source it, there's no magic there... just... garbage (:

Ideally, we move the required *html* + *js* files (both of these are readily accessible via *view source* anyway) onto serverless-dns instead #1

**Comment by lwd-temp** [comment]
> We could open source it, there's no magic there... just... garbage (:
> 
> Ideally, we move the required _html_ + _js_ files (both of these are readily accessible via _view source_ anyway) onto serverless-dns instead #1

That would be great, because `rethinkdns.com` is blocked in some area (China Mainland, for example), and users from there won't configure the serverless DNS.

**Comment by ignoramous** [comment]
Noted; closing this bug in favour of #1.
