### ISSUE TITLE
Google as dns resolvers?

### ISSUE THREAD

**Issue by suricloud** [serverless-dns/serverless-dns#170]
Hi,
I have serverless dns self hosted on cloudflare.But when i do  a dns leak test i see google servers and not cloudflare??
Can you please check and fix this?

**Comment by ignoramous** [comment]
Hi, see this for an explanation (and potential resolution): https://github.com/serverless-dns/serverless-dns/issues/168

Also, the query is *proxied* from Cloudflare with all user-relevant information dropped from the query; that is, the Google servers only see it as Cloudflare Servers making the request and ideally won't know much ([unless they really bothered](http://dnscookie.com/)) about which particular IP / user is making those.
