### ISSUE TITLE
Auto-schedule deploys

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/serverless-dns#171]
> For Cloudflare Workers, you don't really have to update often, but I'd suggest updating it at least once a year. For deployments to Fly.io, I'd suggest keeping in sync with this repo, as performance improvements and optimizations are still on-going.
>
> You should consider however re-deploying (the same code even) weekly / monthly to get the latest blocklists (which are updated on [1st / 8th / 16th / 24th of every month](https://github.com/serverless-dns/blocklists/blob/188f0565dc98242b49c9ac836009b9f0f343fdff/.github/workflows/createUploadBlocklistFilter.yml#L5-L6)).
>
> For example, to deploy to Cloudflare Workers on 2nd / 9th / 17th / 25th, add to your cf.yml (or equivalent github actions config):
> 
>```
>  on:
>  schedule:
>    # why? github.com/serverless-dns/blocklists/blob/fe92d9b/.github/workflows/createUploadBlocklistFilter.yml#L5-L6
>    # at 1:53 on 2nd, 9th, 17th, 25th of every month
>    - cron: '53 1 2,9,17,25 * *'
>```
> Conditional blocklist update is done by [src/build/pre.sh](https://github.com/serverless-dns/serverless-dns/blob/77fead1b016496a9aadfd0e2911c138cda6dc0a3/src/build/pre.sh) invoked by the [npm prepare](https://github.com/serverless-dns/serverless-dns/blob/77fead1b016496a9aadfd0e2911c138cda6dc0a3/package.json#L14) step during [npm install](https://github.com/serverless-dns/serverless-dns/blob/77fead1b016496a9aadfd0e2911c138cda6dc0a3/.github/workflows/cf.yml#L91) in cf.yml.

It would be a good idea if you could add this schedule as default for cf workers.
The blocklist should be updated regulary and automatically.

_Originally posted by @suricloud in https://github.com/serverless-dns/serverless-dns/discussions/149#discussioncomment-6282260_

**Comment by suricloud** [comment]
+1 for this, will be peace of mind for self hosted :)

**Comment by ShailendraMadarie** [comment]
When will this  be updated,because i see many blocklist list a are not up to date when self hosted on cloudflare.

**Comment by ignoramous** [comment]
> When will this be updated,because i see many blocklist list a are not up to date when self hosted on cloudflare.

Can't just add a `schedule` to `cf.yml` because Workers only have 128MB RAM, and the lists are already at 80MB (in collective size) today. So, before updating newer lists, one must check (manually) if the latest update isn't going to break Workers. This isn't automated yet, but expect it to happen once I finish working on https://github.com/celzero/rethink-app/issues/946

In the meanwhile, redeploy and the latest blocklists (which are 79MB in size) should be picked up.

**Comment by suricloud** [comment]
I redeployed,

but hagezi pro plus still shows 386735 entries
       hagezi tif shows  703520

How to get these updated on selfhosted cloudflare workers.

**Comment by suricloud** [comment]
I also added the schedule to my cf.yml file, but the hagezi pro plus and tifs are not updated i see.
can you please check

**Comment by ignoramous** [comment]
Can you post share a link to your recent GitHub Actions deployment if it is open to public?

**Comment by ignoramous** [comment]
cf and fly deploy to `prod` env every week: https://github.com/serverless-dns/serverless-dns/commit/47a9bf1aafd53c37656addc06ad452261b255e46

likely that forks of this repository are using `dev` env and not `prod`, so it may not actually auto-deploy *anywhere* in those cases.
