### ISSUE TITLE
Nothing works when using rethink app

### ISSUE THREAD

**Issue by Lucas559-noob** [serverless-dns/serverless-dns#180]
Since the update, nothing works when I connect the dns, every log say 0ms, there is a way to fix this?

**Comment by ignoramous** [comment]
v055a is out with the fixes: [play store](https://play.google.com/store/apps/details?id=com.celzero.bravedns) and [website](https://rethinkdns.com/download).

That should have fixed the issue you're seeing. Please re-open if that isn't the case. Thanks.
