### ISSUE TITLE
✘ [ERROR] Command failed with exit code 1: npm run build

### ISSUE THREAD

**Issue by suricloud** [serverless-dns/serverless-dns#181]
Hi,

I just synced  the forked,and see the its failing on cloudflare?

✘ [ERROR] Command failed with exit code 1: npm run build

Please check and fix the issue.

**Comment by ignoramous** [comment]
My bad, fixed it: https://github.com/serverless-dns/serverless-dns/commit/5e442ff00e835f234daf9307748465131bc605c6
