### ISSUE TITLE
CF: All jobs have failed

### ISSUE THREAD

**Issue by suricloud** [serverless-dns/serverless-dns#186]
Hi,

The autoschedule for weekly updates failed on cloudflare.
Can you please check and fix it.

[Deploy worker
▲ [WARNING] The current authentication token does not have 'All Zones' permissions.

  Falling back to using the zone-based API endpoint to update each route individually.
  Note that there is no access to routes associated with zones that the API token does not have permission for.
  Existing routes for this Worker in such zones will not be deleted.

✘ [ERROR] Could not find zone for sky.rethinkdns.com

--

`npx wrangler deploy --env prod` returned non-zero exit code.

------------------

Action failed

**Comment by ignoramous** [comment]
The latest auto scheduled job succeeded: https://github.com/serverless-dns/serverless-dns/actions/runs/6390243767

> ERROR] Could not find zone for sky.rethinkdns.com

`sky.rethinkdns.com` is a zone I own. Unlikely your account has the privilege to deploy to it.

auto scheduled deploys won't work out of the box. Probably needs tweaking the `wrangler.toml` file and the workflow file itself.

**Comment by suricloud** [comment]
i just redployed again,and seems to ok now.

**Comment by ignoramous** [comment]
It fixed on its own? Strange. Closing... (please feel free to reopen if you see this happen again).

**Comment by suricloud** [comment]
auto schedule update for cloudflare failed again ?

Run cloudflare/wrangler-action@v3
📥 Installing Wrangler
🚀 Running Wrangler Commands
Error: `npx wrangler deploy --env prod` returned non-zero exit code.
Error: 🚨 Action failed

**Comment by ignoramous** [comment]
> --env prod

You probably don't have a `prod` env in `wrangler.toml`.

**Comment by suricloud** [comment]
How to get this prod env in wrangler.toml ?

Isn't it automaticaly created when i fork to cloudflare and sync?
Or should i delete all and do it all again fresh.

**Comment by ignoramous** [comment]
Yeah, this was always going to be a problem... You can create a `prod` env by adding a `prod` section in `wrangler.toml` until I can think of something better that works for *forks*.

**Comment by lamminh2012** [comment]
Hi @ignoramous
Could you please tell me how to fix these errors as shown in log?

Your worker has access to the following bindings:
 - Vars:
   - LOG_LEVEL: "info"
   - WORKER_ENV: "production"
   - CLOUD_PLATFORM: "cloudflare"
 Total Upload: 261.96 KiB / gzip: 74.08 KiB
 Uploaded basic-unbound (0.98 sec)
 
 ✘ ERROR A request to the Cloudflare API (/accounts/***/workers/scripts/basic-unbound/routes) failed.
 
   workers.api.error.zone_not_specified - Can't infer zone from route, please specify zone for "sky.rethinkdns.com/*" [code: 10082]
   workers.api.error.zone_not_specified - Can't infer zone from route, please specify zone for "sky.bravedns.com/*" [code: 10082]
   workers.api.error.zone_not_specified - Can't infer zone from route, please specify zone for "basic.rethinkdns.com/*" [code: 10082]
   workers.api.error.zone_not_specified - Can't infer zone from route, please specify zone for "basic.bravedns.com/*" [code: 10082]
   workers.api.error.zone_not_specified - Can't infer zone from route, please specify zone for "free.bravedns.com/*" [code: 10082]   
   If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
Z 
 ##[endgroup]
 ##[error]`npx wrangler deploy --env prod` returned non-zero exit code.
 ##[error]🚨 Action failed

Thanks for your help.

**Comment by ignoramous** [comment]
You'd need to change `wrangler.toml` to values relevant to your DNS zone. `bravedns.com` and `rethinkdns.com` are zones that we own and maintain, to which, of course you'd not be able to dpeloy.

**Comment by suricloud** [comment]
again auto schedule update on cloudflare fails ?

Run cloudflare/wrangler-action@v3
📥 Installing Wrangler
🚀 Running Wrangler Commands
Error: The process '/usr/local/bin/npx' failed with exit code 1
Error: 🚨 Action failed

**Comment by ignoramous** [comment]
Sounds like that's a failure to either build or bundle `serverless-dns`. Is your repo open source?

**Comment by suricloud** [comment]
yes it is

**Comment by suricloud** [comment]
I do get this error now on auto schedule

Error: The process '/usr/local/bin/npx' failed with exit code 1
Error: 🚨 Action failed
