### ISSUE TITLE
Certificate expired on https://max.rethinkdns.com/rec

### ISSUE THREAD

**Issue by caboose89** [serverless-dns/serverless-dns#191]
The certificate on https://max.rethinkdns.com/rec expired two days ago and now resolution is not working because of this.
Please can you issue a new certificate?
Thanks

**Comment by ignoramous** [comment]
We've now automated cert changes without requiring new deployments: https://github.com/serverless-dns/serverless-dns/commit/21afa97411240f74b9b0d22898070ebf246eb51c

Fly.io, which hosts `max.rethinkdns.com`, vends out updated certs (which are stored as "[secrets](https://fly.io/docs/flyctl/secrets/)") only after a *new* deployment. And they block deployments if the bills are over due (which is routinely the case for us as we have to scramble to pay the bills, which may or may not happen in time for "secrets" to get new certs through).

With the new changes, if the certs in-use are close to expiry, the servers on Fly.io will ask for new certs from our vault hosted on Cloudflare and use them if they are latest.
