### ISSUE TITLE
RethinkDNS DoH and configuration page doesn't work

### ISSUE THREAD

**Issue by tina-hello** [serverless-dns/serverless-dns#194]
Got 429 on the DoH, and the configuration page gives TypeError: Failed to fetch; version: v23.9

**Comment by ronak360** [comment]
I am facing same issues

**Comment by lamminh2012** [comment]
> Got 429 on the DoH, and the configuration page gives TypeError: Failed to fetch; version: v23.9

It's now working again (Nov 29)
