### ISSUE TITLE
DNS (CF wokers) not working

### ISSUE THREAD

**Issue by liangchaPLUS** [serverless-dns/serverless-dns#195]
I've set a custom domain point to serverless-dns worker on cloudfalre.
The dns was working just fine a few days ago.

Github workflows reported this error yestaerday:
workflow failure:
🚀 Deploy workerThe process '/usr/local/bin/npx' failed with exit code 1
🚀 Deploy worker🚨 Action failed

And now the dns isn't working.
When I open its website it gives an error:
TypeError: Failed to fetch; version: v23.9 (3). Please try after sometime.

**Comment by JohanChungus** [comment]
I have same problem too

**Comment by kloudxyz** [comment]
i get this error:

npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2023-11-22T10_31_54_199Z-debug-0.log
Error: Process completed with exit code 1.

**Comment by GIorfindel** [comment]
Same for me, I get this error:
```
> ./src/build/pre.sh
x=== pre.sh: 0 try 2023/11-4 at 1700926215 from /home/runner/work/serverless-dns/serverless-dns
==x= pre.sh: 0 not ok 4
x=== pre.sh: 1 try 2023/11-3 at 1700926215 from /home/runner/work/serverless-dns/serverless-dns
==x= pre.sh: 1 not ok 4
x=== pre.sh: 2 try 2023/11-2 at 1700926215 from /home/runner/work/serverless-dns/serverless-dns
==x= pre.sh: 2 not ok 4
x=== pre.sh: 3 try 2023/11-1 at 1700926215 from /home/runner/work/serverless-dns/serverless-dns
==x= pre.sh: 3 not ok 4
x=== pre.sh: 4 try 2023/10-5 at 1700926215 from /home/runner/work/serverless-dns/serverless-dns
==x= pre.sh: 4 not ok 4
npm ERR! code 1
npm ERR! path /home/runner/work/serverless-dns/serverless-dns
npm ERR! command failed
npm ERR! command sh -c ./src/build/pre.sh
npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2023-11-25T15_29_40_519Z-debug-0.log
Error: Process completed with exit code 1.
```

**Comment by ignoramous** [comment]
The blocklists uploads were failing because our infrastructure provider (Cloudflare) had pulled the rug from underneath our account citing a 'trust and safety' issue (though, we don't know what exactly the issue is, as no one has informed us). Though our account still remains hamstrung, I've managed to rewrite some parts of the code and have blocklists uploads (and downloads) working again. See if deploys now work?

**Comment by liangchaPLUS** [comment]
Seems everything is working again. Thanks for the work.
