### ISSUE TITLE
Fly.io blocklist not working

### ISSUE THREAD

**Issue by dng-nguyn** [serverless-dns/serverless-dns#196]
I've set my domains `dns.example.com` and `*.dns.example.com` to point to the shared ipv4 and dedicated ipv6 of the instance running the dns. When setting Private DNS for Android, It works okay as a dns resolver and results from dnsleak shows that I'm using the dns. However, when setting up the dns for blocking content `1-abc...dns.example.com`, everything gets resolved as normal, but nothing is getting blocked.

**Comment by dng-nguyn** [comment]
Update: It works, was issue on my end while setting DNS record. the `*.dns.example.com` isn't supposed to be there.

**Comment by ignoramous** [comment]
That's strange. Can you share the domain to your instance over email (and reference this issue) so I may check? `mz` at `celzero` dot `com`.

If your fork is openly accessible, will you please link to it?

**Comment by ignoramous** [comment]
(pls feel free to reopen with a reply)
