### ISSUE TITLE
Add more DNS_RESOLVER Variable to code

### ISSUE THREAD

**Issue by nightmare199x** [serverless-dns/serverless-dns#199]
According to the code in the worker, there are only 2 DNS_RESOLVER added, is there any way to add more?

Currently I am setting cloudflare's variable like this:
Variable name Value
CF_DNS_RESOLVER_URL https://dns.nextdns.io
CF_DNS_RESOLVER_URL_2 https://dns.google/dns-query
CLOUD_PLATFORM cloudflare
LOG_LEVEL debug
WORKER_ENV development

Now I want to add DNS3 (cloudflare), DNS4 (OpenDNS).
Is this possible?
Thank you very much!

**Comment by tina-hello** [comment]
You'd have to add their references after https://github.com/serverless-dns/serverless-dns/blob/b003bd93f546f7ce7a1d19a8fb83c6071f70f4b4/src/commons/envutil.js#L113 and also modify https://github.com/serverless-dns/serverless-dns/blob/b003bd93f546f7ce7a1d19a8fb83c6071f70f4b4/src/commons/envutil.js#L142 to include the rest

**Comment by nightmare199x** [comment]
im hosting on Cloudflare worker, where should i do that?

> You'd have to add their references after
> 
> https://github.com/serverless-dns/serverless-dns/blob/b003bd93f546f7ce7a1d19a8fb83c6071f70f4b4/src/commons/envutil.js#L113
> 
> and also modify
> https://github.com/serverless-dns/serverless-dns/blob/b003bd93f546f7ce7a1d19a8fb83c6071f70f4b4/src/commons/envutil.js#L142
> 
> to include the rest

**Comment by tina-hello** [comment]
Edit them in your fork and deploy to your own worker

**Comment by nightmare199x** [comment]
> Edit them in your fork and deploy to your own worker

it returns with error when commit:

Run denoland/deployctl@1.4.0
Project: rdns
Entrypoint: file:///src/rethinkdns.js
Error: APIError: The authorization token is not valid: You don't have permission to access the project 'rdns'. Please ensure your workflow file references the correct project
x-deno-ray: 8cd34769697ed4b6d6dff50ca73af709
If you encounter this error frequently, contact us at deploy@deno.com with the above x-deno-ray.

**Comment by nightmare199x** [comment]
Hello,
In the Worker - serverless-setting-variable, i setup like this with nextdns + google:
<html>
<body>

Variable name | Value
-- | --
CF_DNS_RESOLVER_URL | https://dns.nextdns.io/
CF_DNS_RESOLVER_URL_2 | https://dns.google/dns-query
CF_DNS_RESOLVER_URL_3 | https://cloudflare-dns.com/dns-query
CLOUD_PLATFORM | cloudflare
LOG_LEVEL | debug
WORKER_ENV | development


</body>
</html>

But in the code of Worker, the default code is as below with Cloudflare + Google:
// url to blocklist files: trie (td), rank-dir (rd), metadata: (filetag)
      CF_BLOCKLIST_URL: {
        type: "string",
        default: "https://cfstore.rethinkdns.com/blocklists/"
      },
      // primary doh upstream
      CF_DNS_RESOLVER_URL: {
        type: "string",
        default: "https://cloudflare-dns.com/dns-query"
      },
      // secondary doh upstream
      CF_DNS_RESOLVER_URL_2: {
        type: "string",
        default: "https://dns.google/dns-query"
      },
      // upstream recursive rethinkdns resolver running on Fly.io
      MAX_DNS_RESOLVER_URL: {
        type: "string",

Do i have to edit the code of Worker as well? 
Thanks!

> Edit them in your fork and deploy to your own worker

**Comment by ignoramous** [comment]
>  CF_DNS_RESOLVER_URL_3 | https://cloudflare-dns.com/dns-query
