### ISSUE TITLE
Support GET requests

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/serverless-dns#2]
`GET` requests are broken when stamps are used.

Tested at [dohjs.org](https://dohjs.org/)

With URLs

 ```
https://basic.bravedns.com/dns-query/1:AMD_PwDw

https://basic.bravedns.com/1:AMD_PwDw
```

**Comment by tina-hello** [comment]
With unstamped https://basic.bravedns.com/ the GET requests work, but with self-deployed Cloudflare instance, both stamped and unstamped GET requests don't work.

**Comment by santhosh-ponnusamy** [comment]
@tina-hello 
https://github.com/serverless-dns/serverless-dns/commit/347a44b510a11bad92ef64b771e7ed93bdfbb5af with this commit dns over http get request has been fixed.

Tested at https://dohjs.org/

with following url

https://basic.bravedns.com/dns-query/1:AMD_PwDw

https://basic.bravedns.com/1:AMD_PwDw
