### ISSUE TITLE
WiFi connection problem

### ISSUE THREAD

**Issue by Horizonbli** [serverless-dns/serverless-dns#20]
First of all, I searched for "wifi", and couldn't find any similar issue.
That said, I created a WiFi hotspot using a mobile device. After connecting to it, I get no dns queries. The same happens with public WiFi. It connects, but no dns response.
If I create a Bluetooth hotspot, then it works well.
I tried to add dns ips into wifi settings, but didn't help.

Thanks

**Comment by ignoramous** [comment]
Hi

I'm confused. Are you using the RethinkDNS app or the RethinkDNS resolver? If you're using the latter, then on which OS?

**Comment by Horizonbli** [comment]
Yes, that is correct. If I open the web browser and try to open a site, I get an error saying that "dns probe started". Not sure if it helps.
RethinkDNS dns log shows "send fail".

**Comment by Horizonbli** [comment]
Ok. I figured out the problem. For some reason when I set the hotspot wps connection with pin number, it won't work. But if I choose press button, then it works fine.

**Comment by ignoramous** [comment]
Thanks for reporting back. For captive-portal related issue, let's track it at celzero/rethink-app/issues/59

Closing this issue. Re-open if you think there's more to discuss. Thx again.
