### ISSUE TITLE
Cannot add Rethink DNS `max.rethinkdns.com` to AdGuard apps

### ISSUE THREAD

**Issue by ameshkov** [serverless-dns/serverless-dns#201]
We've got a report from a user that they cannot use Rethink DNS in AdGuard apps. Technically, the problem is that when AdGuard apps verify DNS availability, they attempt to resolve `ipv4only.arpa` domain and check that it returns an IPv4 record.

The problem is that `max.rethinkdns.com` returns an empty NOERROR in response and AG apps consider the check failed.

```
dnslookup ipv4only.arpa https://max.rethinkdns.com/          
dnslookup 1.11.1
Server: https://max.rethinkdns.com/

dnslookup result (elapsed 679.643916ms):
;; opcode: QUERY, status: NOERROR, id: 4023
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ipv4only.arpa.	IN	 A
```

**Comment by ignoramous** [comment]
Thanks.

Does the AdGuard client expect us to reply with rfc7050 addresses (`192.0.0.170`, `192.0.0.171`)?

> attempt to resolve ipv4only.arpa domain and check that it returns an IPv4 record

Could also consider testing the resolver with its own fqdn (`max.rethinkdns.com` in this case) as a fallback when `ipvonly.arpa` fails?

**Comment by ameshkov** [comment]
> Does the AdGuard client expect us to reply with rfc7050 addresses (192.0.0.170, 192.0.0.171)?

Correct, it expects that.

> Could also consider testing the resolver with its own fqdn (max.rethinkdns.com in this case) as a fallback when ipvonly.arpa fails?

Well, the idea of using a domain specified in an RFC is a universal way to check if resolver is working correctly. Using its own fqdn won't work for the case when the user enters IP address and not a domain name.

**Comment by ignoramous** [comment]
Not us: https://community.fly.io/t/21912 :D

**Comment by ignoramous** [comment]
Fix deployed. Thanks for the bug report.

```sh
# doh
sending GET request to https://max.rethinkdns.com:443/rec?dns=pmwBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ 

headers: map[Accept:[application/dns-message] Cache-Control:[public, max-age=76636] Connection:[keep-alive] Content-Length:[89] Content-Type:[application/dns-message] Date:[Sat, 28 Sep 2024 23:53:14 GMT] X-Nile-Region:[bom]];

size: 288

answers:
ipv4only.arpa. 21h17m16s A 192.0.0.170
ipv4only.arpa. 21h17m16s A 192.0.0.171

# dot
kdig @max.rethinkdns.com:853 ipv4only.arpa -d +tls-sni=max.rethinkdns.com
;; QUESTION SECTION:
;; ipv4only.arpa.      		IN	A

;; ANSWER SECTION:
ipv4only.arpa.      	76564	IN	A	192.0.0.171
ipv4only.arpa.      	76564	IN	A	192.0.0.170

;; Received 89 B
```
