### ISSUE TITLE
Redirects dns request to 0.0.0.0 Problem

### ISSUE THREAD

**Issue by p2pproccessor** [serverless-dns/serverless-dns#205]
I wrote it with the help of Google Translate. If there is anything that is not understood, please excuse me.

I completed the installation by following the steps here:

https://blog.leminhthanh.me/2022/03/25/run-your-rethinkdns-on-cloudflare-workers/

I added it to DoH adress to rethinkdns app. I can't access the internet

![rethinkdns](https://github.com/user-attachments/assets/acf25e2e-443e-4316-8194-5f5c61963d8f)

![chrome](https://github.com/user-attachments/assets/6067ec7a-f930-4cc9-9671-56ab93c0c32f)

When I tested it on this site, it redirected to the 0.0.0.0 IP address.

https://dnsleaktest.org/dns-over-https 
![dnstest](https://github.com/user-attachments/assets/60c92d2c-960a-4109-8f1d-299c6b8bb7e5)

If I use DoT  I get the error

![dottest](https://github.com/user-attachments/assets/9f0720e8-7df8-4550-8837-1c3be703f3ac)
![dot](https://github.com/user-attachments/assets/0b9f0105-3ee1-481b-b65d-6c91c6d2530f)

I can only access the internet if I make this setting in Windows. 

![windows](https://github.com/user-attachments/assets/e5105f7f-cf69-41fb-9ae9-fe7b523ed44d)

![adblocktest](https://github.com/user-attachments/assets/29f8455d-9ec4-4062-ba79-457b03c7f563)

--Regardless of the problem, will using it this way on Windows cause a leak in the doh connection?

If there is a log I need to send I can send it, thanks in advance.

**Comment by ignoramous** [comment]
Can you share the blockstamp? The part after `https;//...workers.dev` that starts with `1:`? It is likely some blocklist you've selected is blocking `google.com`.

> Regardless of the problem, will using it this way on Windows cause a leak in the doh connection?

Sorry I can't help. I don't use Windows and do not know what those settings are.

**Comment by p2pproccessor** [comment]
Thank you soo much. You are right. These two block lists are blocking my access to Google. I'm a bit of a newbie so I didn't notice.

Bad Top-Level Domains (cbuijs)↗
Bad Sites (phishing.mailscanner.info + MalwareFilter)↗

DoH problem solved but DoT still not working.

Blockstamp is:

1-7c7qaoaeab7qh67j3p7seqne4aaba5ftfaaeq2qaja.serverless-dns...

ERR_NAME_NOT_RESOLVED error in the browser.

I try visit these websites

google.com
github.com
duckduckgo.com
kernel.org

**Comment by ignoramous** [comment]
> DoH problem solved but DoT still not working.

Cloudflare Workers only supports DoH not DoT. For DoT, you'd have to deploy to `Fly.io`, which is a bit more involved and complicated.

**Comment by p2pproccessor** [comment]
I understand, thank you. I'm closing the issue. I wish you a good day.

**Comment by p2pproccessor** [comment]
I understand, thank you. I'm closing the issue. I wish you a good day.
