### ISSUE TITLE
bluegreen deployment strat on Fly

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/serverless-dns#39]
Okay, let's switch to `bluegreen`, even if it is more ambitious than a `canary`. Hopefully our testing in `dev` environment eliminates cause of such ambitious deployment strat.

_Originally posted by @ignoramous in https://github.com/serverless-dns/serverless-dns/issues/37#issuecomment-1000861881_

**Comment by ignoramous** [comment]
> A: Downtime is still 30s. I had said bluegreen was stable because when OOM problems existed, this strategy had least crashes.
> 4 new instances boot-up, but it takes about 30s for fly proxy to switch the traffic.
> It's probably better to have rolling ? The default is supposed to be rolling after 1st instance (acc. to docs), but in practice, what happens is immediate.

> M: When you say 30s downtime, do you mean zero instance running code?

> A: No, couldn't connect. Instances do come up, but possibly requests go to old instances which are shutdown.

> K: "It takes up to 2 minutes for our edges to see that a VM has changed state. But once a VM stops accepting connections, we retry immediately."
> https://community.fly.io/t/high-availability-on-fly-io/3448/3

**Comment by ignoramous** [comment]
@amithm7 anything left to be done here? What's the status? Link commits, if any, please, and close this issue, as approp. Thx.

**Comment by amithm7** [comment]
This is done, set to `rolling` currently.

https://github.com/serverless-dns/serverless-dns/blob/2713cb27299a5092ee2cefdd66d29099bff5bf9c/.github/workflows/fly.yml#L62
