### ISSUE TITLE
set header exception

### ISSUE THREAD

**Issue by santhosh-ponnusamy** [serverless-dns/serverless-dns#42]
visiting `https://serverless-dns.rethinkdns.com/config` from the browser, throws exception:

```
"TypeError: Can't modify immutable headers.
    at Le.setCorsHeaders (worker.js:28:43577)
    at worker.js:38:1904"
```

https://github.com/serverless-dns/serverless-dns/blob/22f35bfa32673b98664b0720c7b3b0ea63acd2cc/src/index.js#L65
https://github.com/serverless-dns/serverless-dns/blob/26e6629767526f5b98d7f67def6a481ed9bd054a/src/helpers/currentRequest.js#L134

**Comment by amithm7** [comment]
It's interesting, that this is not happening with successful dns queries.

Happens with 503.

Even though it throws error in the loop (at first iteration), all 3 headers are magically set in response!!!

I fail to understand this behavior.

```
❯ curl -v \
  'http://localhost:8787/config' \
  -H 'User-Agent: Mozilla/5.0 something' --output -

* Connected to localhost (127.0.0.1) port 8787 (#0)
> GET /config HTTP/1.1
> Host: localhost:8787
> Accept: */*
> User-Agent: Mozilla/5.0 something
> 

< HTTP/1.1 503 Service Unavailable
< date: Thu, 30 Dec 2021 13:42:28 GMT
< content-type: application/json
< content-length: 159
< connection: keep-alive
< access-control-allow-origin: *
< access-control-allow-headers: *
< access-control-allow-methods: GET, POST, OPTIONS

< vary: Accept-Encoding
< 
* Connection #0 to host localhost left intact
"TypeError: Can't modify immutable headers.\n    at currentRequest_CurrentRequest.setCorsHeaders (worker.js:7182:33)\n    at proxyRequest (worker.js:10137:57)"%
```

**Comment by amithm7** [comment]
fixed!

**Comment by amithm7** [comment]
@ignoramous 

The `TypeError` is coming from Headers Guard set to "immutable". See: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#guard . It is not exposed, so we can't check if a Response is immutable...

The 302 redirect response which is "immutable" here comes from it being constructed with `Response.redirect()` method.
https://github.com/serverless-dns/serverless-dns/blob/b6ebf7a83dc480a0819966ab5e11e7fc8269a397/src/command-control/cc.js#L156

which sets the headers guard to "immutable". See: https://fetch.spec.whatwg.org/#dom-response-redirect (Step 4)

**Comment by ignoramous** [comment]
Nice find. We should create headers when `Response` obj is constructed to avoid runtime issues?

**Comment by amithm7** [comment]
Creating a new Response there would solve the issue too:

```js
this.httpResponse = new Response(this.httpResponse.body, {
  headers: util.concatHeaders(
    this.httpResponse.headers,
    util.corsHeaders()
  ),
});
```

Or a try catch ? (I prefer this).

**Comment by ignoramous** [comment]
`try-catch` as a conditional? Doesn't fit. Better to not rely on `Response.Headers.set` working at all, since the API is clearly demarcated off-limits in the documentation.

**Comment by amithm7** [comment]
> try-catch as a conditional?

No, like catch TypeErr if gaurd is set.

>  Better to not rely on Response.Headers.set working at all, since the API is clearly demarcated off-limits in the documentation.

I still don't agree with that, ["The headers read-only property of the Response interface"](https://developer.mozilla.org/en-US/docs/Web/API/Response/headers), says only about the "property" being read-only.

**Comment by ignoramous** [comment]
I prefer doing the most consistent thing rather than complect the code with conditionals / guards, try-catch, what have you.

1. These CORS headers added for tests are a maintenance burden.
2. Setting the headers at the time `Response` obj is instantiated is guaranteed to work in all cases (except for forbidden headers).
3. `Headers.set` isn't even a critical design decision to be bike shedding about.

**Comment by ignoramous** [comment]
To be clear, you're free to choose the solution here you think is best. As long as it works, I mean.

**Comment by ignoramous** [comment]
I believe there's nothing much to do here?
