### ISSUE TITLE
Deno Deploy Upstream Error

### ISSUE THREAD

**Issue by knsim24** [serverless-dns/serverless-dns#46]
<html><body>

45 | [Error] | 2022-01-22T15:47:49.753Z E RethinkPlugin [rx.o6wcl2xi55.k9ufww4cca] exception {"isException":true,"exceptionStack":"Error: [rx.o6wcl2xi55.k9ufww4cca]no upstream result\n    at DNSResolver.makeRdnsResponse (file:///src/index.bundle.js:7274:25)\n    at DNSResolver.resolveDns (file:///src/index.bundle.js:7251:30)\n    at DNSResolver.RethinkModule (file:///src/index.bundle.js:7226:40)\n    at async RethinkPlugin.executePlugin (file:///src/index.bundle.js:7597:25)","exceptionFrom":"dnsResolver","data":{}}
-- | -- | --
46 | [Warn] | 2022-01-22T15:52:53.263Z W DnsBlocker [rx.47n5vyse9a.sz3pl3y4nd] q: no stamp
47 | [Error] | 2022-01-22T15:52:53.265Z E DnsResolver [rx.47n5vyse9a.sz3pl3y4nd] main TypeError: Invalid URL     at Object.opSync (deno:core/01_core.js:149:12)     at opUrlParse (deno:ext/url/00_url.js:47:27)     at new URL (deno:ext/url/00_url.js:320:20)     at DNSResolver.resolveDnsUpstream (file:///src/index.bundle.js:7311:26)     at DNSResolver.resolveDns (file:///src/index.bundle.js:7259:32)     at async DNSResolver.RethinkModule (file:///src/index.bundle.js:7226:29)     at async RethinkPlugin.executePlugin (file:///src/index.bundle.js:7597:25)
48 | [Error] | 2022-01-22T15:52:53.265Z E RethinkPlugin [rx.47n5vyse9a.sz3pl3y4nd] exception {"isException":true,"exceptionStack":"TypeError: Invalid URL\n    at Object.opSync (deno:core/01_core.js:149:12)\n    at opUrlParse (deno:ext/url/00_url.js:47:27)\n    at new URL (deno:ext/url/00_url.js:320:20)\n    at DNSResolver.resolveDnsUpstream (file:///src/index.bundle.js:7311:26)\n    at DNSResolver.resolveDns (file:///src/index.bundle.js:7259:32)\n    at async DNSResolver.RethinkModule (file:///src/index.bundle.js:7226:29)\n    at async RethinkPlugin.executePlugin (file:///src/index.bundle.js:7597:25)","exceptionFrom":"dnsResolver","data":{}}
49 | [Error] | Error: no upstream     at DNSResolver.resolveDnsUpstream (file:///src/index.bundle.js:7303:24)     at DNSResolver.resolveDns (file:///src/index.bundle.js:7259:32)     at async DNSResolver.RethinkModule (file:///src/index.bundle.js:7226:29)     at async RethinkPlugin.executePlugin (file:///src/index.bundle.js:7597:25)

</body>
</html>

**Comment by ignoramous** [comment]
Yikes. Is Deno Deploy completely down due to this error?

**Comment by ignoramous** [comment]
This may be the fix: https://github.com/serverless-dns/serverless-dns/commit/995f4dc71932401c1a38c942ae9a87f931e8f6f1

Can you please test? (I should get my act straight and treat Deno deploys more seriously).

**Comment by knsim24** [comment]
0 | doh proxy-request error TypeError: Cannot read properties of undefined (reading 'bind')     at new RethinkPlugin (file:///src/index.bundle.js:7551:62)     at proxyRequest (file:///src/index.bundle.js:7729:24)     at handleRequest (file:///src/index.bundle.js:7723:12)     at serveHttp (file:///src/index.bundle.js:7813:19)
-- | --

Here is the updated logs after 7c04a5d update for your references. I skip to the latest logs without hostname address(my ip).

**Comment by ignoramous** [comment]
Strangely, local Deno setup works just fine... Is it `deno bundle` that's stricter here...?

Another attempt to get Deno deploy to work: https://github.com/serverless-dns/serverless-dns/commit/8a705409e239e3da0479293cd45c5e2d0d21afbf

**Comment by knsim24** [comment]
0 | 2022-01-23T16:09:57.748Z W Deno serv fail doh request Error: missing request     at mkFetchEvent (file:///src/index.bundle.js:7890:28)     at serveHttp (file:///src/index.bundle.js:7816:33)
-- | --
1 | 2022-01-23T16:09:57.747Z W Deno serv fail doh request Error: missing request     at mkFetchEvent (file:///src/index.bundle.js:7890:28)     at serveHttp (file:///src/index.bundle.js:7816:33)
2 | 2022-01-23T16:09:57.040Z W Deno serv fail doh request Error: missing request     at mkFetchEvent (file:///src/index.bundle.js:7890:28)     at serveHttp (file:///src/index.bundle.js:7816:33)
3 | 2022-01-23T16:09:57.033Z I Deno DoH listening on: [127.0.0.1]:80
4 | not workers, no-op http-cache-api
5 | svc: systemReady
6 | Console level set:  info

Heres the latest log for the update 8a70540

**Comment by ignoramous** [comment]
cc: @amithm7 

I am out of ideas on why Deno works locally but not on Deno Deploy. I believe the current error might have something to do with function overloading / type mismatch between how mkFetchEvent is defined ([`mkFetchEvent(Request, Function[])`](https://github.com/serverless-dns/serverless-dns/blob/465223d6/src/server-deno.ts#L201)) versus how it is called ([`mkFetchEvent(Request, Function)`](https://github.com/serverless-dns/serverless-dns/blob/465223d6/src/server-deno.ts#L110))?

**Comment by ignoramous** [comment]
I think I may have _unwittingly_ fixed the error: https://github.com/serverless-dns/serverless-dns/commit/e3deac7ab7e6366f350c1ce991e8def8ea824566 ;)

**Comment by amithm7** [comment]
@ignoramous 

We have our own logs here: https://dash.deno.com/projects/rdns

Issue is that `env.runTime` mapping has a default value.

Logs from deno-deploy (read bottom-up):

```
[Debug]	Added runTime node
[Warn]	runTime env[key] default value: node
[Info]	Loading env. from runtime: deno
[Warn]	Deno.env.set() is not available =>  TypeError : Can not modify env vars during execution.
[Warn]	.env file may not be loaded =>  TypeError : Deno.readFileSync is not a function
[Debug]	isolate start time: 996 milliseconds
```

https://github.com/serverless-dns/serverless-dns/blob/e3deac7ab7e6366f350c1ce991e8def8ea824566/src/core/env.js#L25-L29

This is not affecting locally, as `Deno.env.set()` works, but not on deno-deploy.

https://github.com/serverless-dns/serverless-dns/blob/e3deac7ab7e6366f350c1ce991e8def8ea824566/src/core/deno/config.ts#L35-L41

IMO, runtime, cloud platform, etc. shouldn't have defaults.

`env.runTime` is prgrammatically handled:

https://github.com/serverless-dns/serverless-dns/blob/e3deac7ab7e6366f350c1ce991e8def8ea824566/src/core/env.js#L190-L194

---

Also, I saw that alpn was added to deno DoH, but Deno's `unstable` API is [not supported on deno-deploy](https://deno.com/deploy/docs/runtime-api#deno-apis).

**Comment by amithm7** [comment]
fixed.

**Comment by ignoramous** [comment]
Deno must now be up and running... 

Locally Deno (`./run deno`) does work, and I observed our test setup on Deno Deploy does too.

A lot of improvements needed still... So as and when those happen, expect more hiccups ;)
