### ISSUE TITLE
Infinite hot loop on Deno Deploy

### ISSUE THREAD

**Issue by piscisaureus** [serverless-dns/serverless-dns#52]
[`if (!requestEvent) continue;`](https://github.com/serverless-dns/serverless-dns/blob/8d4e77295acc3e4e3978cf408162c7d5b970f874/src/server-deno.ts#L93)

This line causes an infinite hot loop on Deno Deploy. 

Once `HttpConn.nextRequest()` returns null or throws, no more requests will be available on that specific connection, so you should break out of the loop.

**Comment by ignoramous** [comment]
Thanks.

cc: @amithm7 what should be done here? I was of the opinion that the `continue` there exists to read subsequent packets on the same conn (pipelining)... but looks like it isn't the case.

**Comment by ignoramous** [comment]
I guess we are better off using the newer [`http/server` apis](https://deno.land/manual/runtime/http_server_apis#http-server-apis). 

@piscisaureus Didn't realise you were a core Deno contributor... so, I'd defer to your expert opinion that the code must bail when requestEvent is `null`. Thanks for the bug report. Hopefully this fixes the hot-loop: https://github.com/serverless-dns/serverless-dns/commit/1b60d566a72100d53a7e0af3005047bcc5298cde

**Comment by amithm7** [comment]
https://rdns.deno.dev/ shows `503`.

Did the last commit broke it or if the project was suspended due to this error? ( there is a message: "PROJECT_SUSPENDED" !?)  @piscisaureus

**Comment by piscisaureus** [comment]
@amithm7 We had to suspend some projects because they all had multiple deployments stuck in the hotloop. If the issue has been addressed I'll unblock them.
