### ISSUE TITLE
Migrate the codebase to Typescript

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/serverless-dns#56]
The refactor has been painful due to the wild west nature of this javascript codebase. Let's try to  static-type it esp since absence of tests are exaggerating the pain, at this moment.

**Comment by Synergy5761** [comment]
Hi is this still something you are looking for? I would love to give this a try but don't have experience with javascript or Typescript. If it is managable for a beginner, I want to give an attempt.

**Comment by ignoramous** [comment]
Hi: Don't think it is manageable for a beginner, but these AI tools might make it easier.

**Comment by ignoramous** [comment]
jsdoc has served us well.
