### ISSUE TITLE
Unsure Failed Deployments on deno-deploy.

### ISSUE THREAD

**Issue by knsim24** [serverless-dns/serverless-dns#60]
![image](https://user-images.githubusercontent.com/95121651/153129015-664be733-3ae8-4758-b962-e21bcf4e3c0f.png)

After linking to the repo, there is an error as stated above. (1st pic)
Status on https://______.deno.dev/ is currently online and working but the latest changes currently does not push/follow.

**Comment by ignoramous** [comment]
Hm, thanks. Checking.

**Comment by ignoramous** [comment]
It seems like the failure you're seeing isn't caused by any of the recent changes I've made to the code-base. I am also unfortunately out of depth afa deno-deploy is concerned.

tagging @amithm7 for pointers (may have to wait a while though since amith's occupied with other things, atm).

**Comment by knsim24** [comment]
![image](https://user-images.githubusercontent.com/95121651/153552830-a47f482b-523c-45d7-aaf1-eefb4bad4eb9.png)
I have recieve their email regarding this matter for your references.
tbh, i dont have any more issuses to the older ones and just the pushing of new deployments.
Thanks

**Comment by ignoramous** [comment]
Set `CLOUD_PLATFORM` to `deno-deploy` in your environment variables. That shoud prevent usage of dynamic imports:

https://github.com/serverless-dns/serverless-dns/blob/2cd385574cc94c535d503df0d19a9f1df6193832/src/commons/envutil.js#L34-L37

**Comment by ignoramous** [comment]
and/or, mark `DENO_ENV` as `production` in our env vars on deno.com.

**Comment by ignoramous** [comment]
Okay, so you can deploy the tip to deno.com and things should work without setting those env variables... but really, you should be setting those env variables anyway.

https://github.com/serverless-dns/serverless-dns/blob/3d57ff7e7f41185b0b51a8fe04b9168f8fb404aa/src/commons/envutil.js#L21-L29

**Comment by ignoramous** [comment]
Okay, so none of these code changes would make deno/deploy happy. Not sure what they changed 9d days back, but whatever they did, broke our deploys.

There is a workaround in https://github.com/denoland/deploy_feedback/issues/166 but let's wait for a week to see if we would need to employ it.

**Comment by ignoramous** [comment]
I modified the deploy scripts and a bunch of other things to get around the issue we are seeing with deno.com deploys.

This mean, you'd have to "Unlink" the project (on deno.com dashboard) and re-link it with "deployment type" as "GitHub Actions" and branch as "main" (we were using "Automatic" deploys before today, which of course is giving us immeasurable pain).

Ref: [deno/deploy/docs/projects#git](https://deno.com/deploy/docs/projects#git-integration).

@knsim24 let me know if this works. I've also updated [RethinkDNS docs with these new steps](https://docs.rethinkdns.com/dns/open-source#deno-deploy).

**Comment by ignoramous** [comment]
Ah, right... you mean this var should be configurable:

https://github.com/serverless-dns/serverless-dns/blob/f2fbc1c72379c986217c5917c594e6a037650d2d/.github/workflows/deno-deploy.yml#L97

**Comment by knsim24** [comment]
Yes. The user who has different project name set from the deno-deploy project name.
Recondmendation: Rephrase/Add the sentences in the Rethinkdns docs only. (optional).
Thanks.

**Comment by ignoramous** [comment]
Thanks for the pointers. Now, one can setup a github secret `DENO_PROJECT_NAME` to your deno.com project name to avoid making code changes for automated deno-deploys.

I've updated the docs to reflect this, too.

**Comment by knsim24** [comment]
Noted. All latest changes stated above includes the Rethinkdns docs is fine and no issues occur.
Thanks.
