### ISSUE TITLE
Strip headers when making upstream fetch calls

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/serverless-dns#7]
It is likely we are leaking client IP to upstream through headers `x-forwarded-for` and/or `cf-connecting-ip` and/or other headers that may contain that information.

https://stackoverflow.com/questions/61860592/is-it-possible-to-get-a-clients-ip-address-from-http-request-header

**Comment by santhosh-ponnusamy** [comment]
https://github.com/serverless-dns/serverless-dns/commit/347a44b510a11bad92ef64b771e7ed93bdfbb5af
with above commit, passing information to upstream fetch call has been fixed.
It has been tested with nextdns resolver.
