### ISSUE TITLE
Add authorization for DoH

### ISSUE THREAD

**Issue by 3nprob** [serverless-dns/serverless-dns#79]
It would be great if there was some form of rudimentary access control.

The only native viable way I see right now would be to have a static `ACCESS_TOKEN` which is required as part of the DoH URI.

**Comment by ignoramous** [comment]
A singular (and static) access token can be trivially implemented with secrets (supported on all 3 platforms serverless-dns deploys to). Another option would be HTTTP Basic Auth. Though, both these solutions would be DoH-only.

**Comment by 3nprob** [comment]
How is DoH client support for HTTP Basic Auth?

Putting the token in the URI should work in all clients without explicit support. FWIW Android is getting DoH3 now so this could be super useful for that I think.

**Comment by dabeeeenster** [comment]
How are people deploying this platform without auth? Without auth does this not allow the resolver to be used by anyone on the internet with the domain name?

**Comment by ignoramous** [comment]
> Without auth does this not allow the resolver to be used by anyone on the internet with the domain name?

Yes, it does. But it's $1 per 4m DNS requests on Workers (that's ~2 reqs every second for a month), and $2 for any number of requests on Fly. Deno is slightly more expensive.

> How are people deploying this platform without auth?

Auth as a gatekeeping mechanism is overrated when you can change the sub-domain you deploy to, on the fly, for free.

**Comment by dabeeeenster** [comment]
> > Without auth does this not allow the resolver to be used by anyone on the internet with the domain name?
> 
> Yes, it does. But it's $1 per 4m DNS requests on Workers (that's ~2 reqs every second for a month), and $2 for any number of requests on Fly. Deno is slightly more expensive.
> 
> > How are people deploying this platform without auth?
> 
> Auth as a gatekeeping mechanism is overrated when you can change the sub-domain you deploy to, on the fly, for free.

Understood, thanks. So you're advising just deploying to something like `<hash>.<mydomain>.com` ?

**Comment by ignoramous** [comment]
Other people using your DoH endpoint isn't going to cost you much on Workers (besides being cheap, Cloudflare effectively blocks bots just fine and for free).

That said, access token based auth is trivially implemented. I'm on a leave now, but once I return (15 Aug), I'd look to implement it.

**Comment by 3nprob** [comment]
BTW, one thing that could mitigate secrets interception:

Make the configuration variable into `ACCESS_TOKEN_HASH`. The URL is expected to be of the form `...?s=p`, where

* `h` is some hash function e.g. pbkdf2 or sha256
* `h(p) == ACCESS_TOKEN_HASH`

**Comment by wen-long** [comment]
Read this
https://www.reddit.com/r/selfhosted/comments/t3ijex/password_protected_doh_server_configuration/

some dns providers like nextdns.io use the method above

**Comment by ignoramous** [comment]
Finally dusted up the commit from my git stash and pushed it in: (main) https://github.com/serverless-dns/serverless-dns/commit/a36d8be891764338e36306816187cb61795396aa and (minor) https://github.com/serverless-dns/serverless-dns/commit/d9b382641b7b68f44886aa304215ea6ac0e580cb

Steps:

1. Generate auth-token for your `domain.tld`: `https://my.actual.dns.domain.tld/genaccesskey?key=<msg-secret>`
  1. Or, by explicitly supplying a domain name: `https://someone.else.but.trusted.dns.domain.tld/genaccesskey?key=<msg-secret>&dom=<my.actual.dns.domain.tld>`.
3. Set the auth-token (which is in hex) as env var (or secret, or check-in into `env.js`) `ACCESS_KEY`.
4. Send DoH / DoT requests with `msg-secret` as part of the blockstamp.
   1. DoH: `https://dns.rethinkdns.localhost/1:-J8AEH8Dv73_8______-___z6f9eagBA:mypasscode`
   2. DoT: `1-7cpqaed7ao73377t777777767777h2p7lzvaaqa-mypasscode.dns.rethinkdns.localhost` (note that for DoT, the entire blockstamp string `1-...-mypasscode` cannot exceed more than 63 chars.

By default, there's no `ACCESS_KEY` set.

Let me know how it goes for you folks... In my tests, things worked fine.
