### ISSUE TITLE
Configure page does not reflect actual blocklist selection

### ISSUE THREAD

**Issue by vinnyang** [serverless-dns/serverless-dns#88]
![N__PwDg_wP9_97hAEAYCAQAgKDwH1zqAJA=](https://user-images.githubusercontent.com/199069/201254466-10c1cb8a-6bcc-453d-ab3f-ddc02d76a60a.jpg)

Configuration string in screenshot: 1:-N__PwDg_wP9_97hAEAYCAQAgKDwH1zqAJA=

Some blocklists under threat-intelligence-feeds while not being selected in the configuration page, they are shown as included in the Search page. And domains in those deselected blocklists are actually being blocked…

**Comment by ignoramous** [comment]
We made some extensive changes to the way we build and use blocklists... it could be that the search page is wrong. I'll take a look at this rather severe bug the first thing when I get free for another unrelated fire-fight. Thanks a lot for reporting this!

**Comment by ignoramous** [comment]
> And domains in those deselected blocklists are actually being blocked…

You mean the *search* page is accurate?

**Comment by ignoramous** [comment]
Oh wait, I just saw the screenshot of the _search_ page. It is searching from an older version of the blocklists (5 Sep). The current is 12 Nov. Ignore "no matches" (broken right now, will fix it), but `drive.google.com` is blocked by `Bad Sites` which is selected in `1:-N__PwDg_wP9_97hAEAYCAQAgKDwH1zqAJA=`

<details>
<summary>screenshot:</summary>
12 Nov:

![Screenshot 2022-11-14 at 11-56-22 Search RethinkDNS](https://user-images.githubusercontent.com/852289/201590068-80de1e37-2790-4136-a043-224821eb4613.png)
</details>

**Comment by vinnyang** [comment]
Hmmm…my original problem was, as you can see in the left of my screenshot, I did **not** add the two blocklists that block `drive.google.com` in the Configuration page (their buttons still say `Add`), but when I go to the Search page, it says that configuration does contain the 2 blocklists I did not select…

**Comment by vinnyang** [comment]
>  Ignore "no matches" (broken right now, will fix it)
Ahh I think I was also confused by this.

**Comment by ignoramous** [comment]
Okay, after some struggle, everything should be up and running as expected (on the search page, on the configure page). If that isn't the case, let me know.

(if you do, then try testing ([configure](https://rethinkdns.com/configure#1:-N__PwDg_wP9_97hAEAYCAQAgKDwH1zqAJA=), [search](https://rethinkdns.com/search?s=1%3A-N__PwDg_wP9_97hAEAYCAQAgKDwH1zqAIA%3D&q=drive.google.com)) in incognito / private browsing mode just to make sure browser's cache isn't getting in the way of the shiny new js files that contain the fixes).

Feel free to reopen in case the bug isn't really fixed or manifests in some other ui flow.
