### ISSUE TITLE
Unable to start service due to removed VPN profile

### ISSUE THREAD

**Issue by lucidtanooki** [serverless-dns/serverless-dns#89]
Hi there,

it gets a bit complicated here. Let me explain:

1. I installed rethinkDNS
2. I enabled rethinkDNS
3. I activatedAlways-on VPN in Android's VPN settings
4. I uninstalled rethinkDNS (VPN profile got removed this way)
5. I re-installed rethinkDNS
6. Tapping on "Start"

Now I get a message "Always-on VPN is enabled for Rethink. Are you sure you want to stop Rethink anyway?"

1. Tapping settings does not work as there is no VPN profile yet
2. Tapping cancel does nothing
3. Tapping "Stop" does nothing as well

There seems to be some information stored that there was a VPN profile with "always-on" active. But since it's not there anymore I am stuck because I cannot change that.

Any idea how to solve this?

Best regards,
LucidTanooki

Edit: Guess this is wrong here. I filed it at [rethink-app](https://github.com/celzero/rethink-app/issues/673).

**Comment by ignoramous** [comment]
Yep, rethink-app is a better place for this. Closing...
