### ISSUE TITLE
Update deno worker to 1.29.1

### ISSUE THREAD

**Issue by GiddyGoatGaming** [serverless-dns/serverless-dns#93]
Not an issue but rather a suggestion. Deno is currently running on 1.27.1 but there is now the version 1.29.1.

**Comment by ignoramous** [comment]
1.28 also sports [improved NPM support](https://deno.land/manual@v1.28.2/node) and that might mean we can throw away some code that keeps Node-specific code work on Deno too. Thanks for the suggestion.
