### ISSUE TITLE
Bump dependency’s and dev dependency’s

### ISSUE THREAD

**Issue by GiddyGoatGaming** [serverless-dns/serverless-dns#98]
I’ve noticed almost all dependency’s and dev dependency’s have available updates. Some are bigger bumps then others but nevertheless this is the packs that have available updates and to what version
Dependency’s
undici ->5.13

proxy-protocol-js ->4.0.6

dotenv->16.0.3

Dev dependency’s

buffer->v19.2.0?

clinic->12.0.0

eslint->8.29.0

eslint-plugin-prettier->4.2.1

husky->8.0.2

lint-staged->13.0.4

prettier->2.8.0

webpack->5.75.0

webpack-cli->5.0.0

wrangler->2.5.0

**Comment by ignoramous** [comment]
run-time deps, proxy-proto and dotenv aren't yet used. I'll take a look at other development deps, but usually, updating them breaks something or the other ;)

**Comment by amithm7** [comment]
@GiddyGoatGaming Many of the dependencies have caret (`^`) versioning, which means that latest versions are being installed and used (as long as `MAJOR` version, i.e. left-most number, remains unchanged).

And like mentioned above, `MAJOR` changes in dependencies may break things.
